### ISSUE TITLE
add main.py

### ISSUE THREAD

**Issue by platers** [irahorecka/ucheck#1]
Hey, nice project!

From what I understand, to use this I need to clone the repo, and create a main.py with the contents of https://github.com/irahorecka/ucheck#ucheck-is-simple-to-use.

Is there a reason this file isn't included in the repo by default?

**Comment by irahorecka** [comment]
Hey @platers, good question. The reason is `ucheck` is a PyPI package that one can `pip install`; therefore `ucheck` is merely a tool one would use to build their own UCheck-autosubmit application. I did this to simplify code distribution. To make your own Ucheck-autosubmitter, just copy the demo code in the README and save it as `main.py` (or whatever name you'd like)!

The process of using this will be as follows:
1. `$ pip install ucheck` (recommended to use a virtual environment)
2. Make `main.py` with the content of the posted example code, appropriately filling out your UTORid credentials
3. `$ python main.py`

No need to clone the repository :)

**Comment by platers** [comment]
I see, thanks. I was thinking of running it with cron every day, guess I'll make a new repo for that.

**Comment by irahorecka** [comment]
Hey @platers - nice idea. I made a cron job for this on my Raspberry Pi. Here's my crontab schedule to execute the UCheck script every morning @ 8 am. Hope you find it useful:

```bash
SHELL=/bin/bash
0 8 * * * source /home/pi/Desktop/auto_ucheck/venv/bin/activate && DISPLAY=:0 python /home/pi/Desktop/auto_ucheck/main.py
```

Note that I created a virtual environment called `venv`. I'm activating this first via `source` then invoking my `main.py` file. `DISPLAY=:0` is required to boot up the browser driver.
